<script setup>
import { ref, computed, reactive, onMounted, onUnmounted, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { Wallet, Refresh, Document, Shop, Lock } from '@element-plus/icons-vue'
import request from '@/utils/request'
import {useRouter} from 'vue-router'
const router=useRouter()
const actor=JSON.parse(sessionStorage.getItem('account')||'{}')
const merchant=actor.role==='ROLE_UNIT'
const data=ref(null),busy=ref(false),active=ref('overview'),codes=reactive({}),resolutions=reactive({}),persona=ref(sessionStorage.getItem('platformDemoPersona')||'701')
const ruleForm=reactive({quotaMinor:10000,transactionMaxMinor:2000,termDays:30,credentialTtlSeconds:300,reservationTtlSeconds:900})
const personas=[{id:'701',name:'模拟结果控制员 · 701'},{id:'401',name:'账务申请人 · 401'},{id:'402',name:'独立账务复核人 · 402'},{id:'501',name:'异议处理人 · 501'}]
const labels={WAITING_MERCHANT:'待商家发布',PUBLISHED:'待顾客确认',CONFIRMED:'已确认待核销',FULFILLED:'已核销',CANCELLED:'已取消',EXPIRED:'已过期',OPEN:'待收',PARTIAL:'部分已还',SETTLED:'已结清',PENDING:'处理中',FAILED:'失败',CLOSED:'已关闭',EXCEPTION:'差异待复核',DRAFT:'待复核',APPROVED:'已批准（演示）',RESOLVED:'已处理'}
const money=value=>(Number(value||0)/100).toFixed(2)
const date=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—'
const name=order=>order.items.map(i=>i.name).join('、')
const resolutionFor=payment=>data.value?.resolutionRequests?.find(r=>r.repaymentId===payment.id&&r.status==='REQUESTED')
const reservation=order=>data.value?.reservations.find(r=>r.orderId===order.id)
const outstanding=computed(()=>data.value?.receivables.reduce((s,r)=>s+r.outstandingMinor,0)||0)
const reserved=computed(()=>data.value?.reservations.filter(r=>r.status==='HELD').reduce((s,r)=>s+r.amountMinor,0)||0)
const received=computed(()=>data.value?.repayments.reduce((sum,p)=>sum+p.receivedMinor,0)||0)
const unallocated=computed(()=>data.value?.repayments.reduce((sum,p)=>sum+p.unallocatedMinor,0)||0)
const repaid=computed(()=>data.value?.repayments.reduce((s,r)=>s+r.allocations.reduce((n,a)=>n+a.amountMinor,0),0)||0)
const pendingRequests=computed(()=>data.value?.requests.filter(r=>r.status==='WAITING_MERCHANT')||[])
async function load(){const r=await request.get('/credit/overview');if(r.code==='200')data.value=r.data;else ElMessage.error(r.msg)}
async function action(type,payload,msg){if(busy.value)return;busy.value=true;try{const r=await request.post('/credit/'+type,{...payload,personaId:persona.value});if(r.code!=='200')return ElMessage.error(r.msg);ElMessage.success(msg||'本机业务状态已更新');await load()}finally{busy.value=false}}
function result(payment,value){action('simulate-result',{repaymentId:payment.id,reference:payment.reference,merchantUid:payment.merchantUid,amountMinor:payment.amountMinor,currency:'CNY',environment:'SIMULATION',providerEventId:'UI-EVENT-'+payment.id+'-'+value,result:value},value==='CONFIRMED'?'模拟成功结果已处理，请查看实际本金分配':'模拟渠道状态已更新')}
function draftRule(){action('draft-rule',{...ruleForm},'演示规则草稿已提交，需另一人格独立复核')}
watch(persona,value=>sessionStorage.setItem('platformDemoPersona',value))
let timer
const sync=event=>{if(event.key==='mall-ui-data-v2')load()}
onMounted(()=>{load();timer=setInterval(load,30000);window.addEventListener('storage',sync)})
onUnmounted(()=>{clearInterval(timer);window.removeEventListener('storage',sync)})
</script>
<template>
<div class="credit-workspace" v-if="data">
  <div class="credit-workspace-header"><div><h1>{{merchant?'本店先吃后付':'先吃后付 · 平台业务'}}</h1><p>{{merchant?'只展示当前门店的请求、预占交易、应收和还款；不展示顾客跨店总额度或可用额度':'按用户、商家、订单关联同一份本机业务记录；以下人格用于验证职责分离'}}</p></div><div><el-button @click="router.push(merchant?'/merchant/afterSales':'/platform/afterSales')">售后与评价</el-button><el-button :icon="Refresh" @click="load">刷新</el-button></div></div>
  <el-alert type="warning" :closable="false" show-icon title="本机业务演示：没有真实借款、扣款或放款" description="原代码夹具参数与状态规则；不代表正式授信。111/111和页面权限只是体验入口，不能代替生产鉴权。首期保证金与平台结算不适用。"/>
  <div class="credit-stats"><div><span>{{merchant?'本店待核销预占':'全部待核销预占'}}</span><strong>¥{{money(reserved)}}</strong><small>HELD，不是已生成应收</small></div><div><span>{{merchant?'本店待收本金':'全部待还本金'}}</span><strong>¥{{money(outstanding)}}</strong><small>核销后应收剩余本金</small></div><div><span>{{merchant?'本店已核实还款本金':'已实际核减本金'}}</span><strong>¥{{money(repaid)}}</strong><small>已模拟退回 ¥{{money(data.refundSummary?.returnedMinor)}}；现金净额 ¥{{money(received-(data.refundSummary?.returnedMinor||0))}}（待分配 ¥{{money(unallocated)}}）</small></div><div><span>待发布请求</span><strong>{{pendingRequests.length}}</strong><small>尚未预占、未产生应收</small></div></div>
  <div v-if="!merchant" class="persona-toolbar"><span>平台合成人格</span><el-select v-model="persona" style="width:260px"><el-option v-for="p in personas" :key="p.id" :value="p.id" :label="p.name"/></el-select><span>不同职责使用不同 actorId，申请人不能自批</span></div>
  <el-tabs v-model="active">
    <el-tab-pane :label="merchant?'用餐请求':'用户额度总览'" name="overview">
      <template v-if="!merchant"><el-alert :title="data.invariant?'额度守恒核对通过：总额度 = 可用 + 预占 + 待还本金':'额度守恒异常，暂停演示操作'" :type="data.invariant?'success':'error'" :closable="false" style="margin-bottom:16px"/><el-table :data="data.accounts" border><el-table-column prop="userUid" label="顾客UID" min-width="145"/><el-table-column label="总额度"><template #default="{row}">¥{{money(row.totalMinor)}}</template></el-table-column><el-table-column label="可用额度"><template #default="{row}">¥{{money(row.availableMinor)}}</template></el-table-column><el-table-column label="预占"><template #default="{row}">¥{{money(row.reservedMinor)}}</template></el-table-column><el-table-column label="待还本金"><template #default="{row}">¥{{money(row.principalMinor)}}</template></el-table-column><el-table-column label="新增确认"><template #default="{row}"><el-tag :type="row.blocked?'danger':'success'">{{row.blocked?'已阻止':'可用'}}</el-tag><span v-if="row.overdue"> 逾期</span><span v-if="row.disputed"> 待处理异议</span></template></el-table-column></el-table></template>
      <h2>待商家发布的用餐请求</h2><el-table :data="pendingRequests" border><el-table-column prop="id" label="请求号" width="110"/><el-table-column prop="userUid" label="顾客UID" min-width="145"/><el-table-column v-if="!merchant" prop="merchantUid" label="商家UID" width="130"/><el-table-column label="餐品" min-width="220"><template #default="{row}">{{name(row)}}</template></el-table-column><el-table-column label="金额" width="110"><template #default="{row}">¥{{money(row.totalMinor)}}</template></el-table-column><el-table-column prop="remark" label="备注" min-width="150"/><el-table-column label="操作" width="175"><template #default="{row}"><el-button v-if="merchant" type="primary" :disabled="busy" @click="action('publish',{requestId:row.id},'已发布，等待顾客主动确认；此时不占额度')">创建并发布订单</el-button><span v-else>由所属商家发布</span></template></el-table-column></el-table>
    </el-tab-pane>
    <el-tab-pane label="订单与核销" name="orders"><el-table :data="data.orders" border><el-table-column prop="id" label="订单号" width="110"/><el-table-column prop="userUid" label="顾客UID" width="145"/><el-table-column prop="merchantUid" label="商家UID" width="130"/><el-table-column label="餐品 / 金额" min-width="200"><template #default="{row}">{{name(row)}}<br><strong>¥{{money(row.totalMinor)}}</strong></template></el-table-column><el-table-column label="状态" width="145"><template #default="{row}"><el-tag>{{labels[row.status]}}</el-tag><small class="cell-note">{{row.fulfillmentStatus}}</small></template></el-table-column><el-table-column label="截止 / 应收" min-width="195"><template #default="{row}"><span v-if="row.status==='PUBLISHED'">确认截止 {{date(row.expiresAt)}}</span><span v-else-if="row.status==='CONFIRMED'">预占截止 {{date(reservation(row)?.expiresAt)}}</span><span v-else-if="row.receivableId">应收 {{row.receivableId}}</span><span v-else>无应收</span></template></el-table-column><el-table-column v-if="merchant" label="本店操作" min-width="270"><template #default="{row}"><template v-if="row.status==='CONFIRMED'"><el-input v-model="codes[row.id]" placeholder="输入顾客展示的演示核销码" size="default"/><div class="cell-actions"><el-button type="primary" :disabled="busy||!codes[row.id]" @click="action('redeem',{orderId:row.id,credential:codes[row.id]},'已演示核销，生成本店应收；总占用未增加')">核销并生成应收</el-button><el-button :disabled="busy" @click="action('cancel',{orderId:row.id},'已取消并释放预占')">取消</el-button></div></template><el-button v-else-if="row.status==='PUBLISHED'" :disabled="busy" @click="action('cancel',{orderId:row.id},'订单已取消')">取消未确认订单</el-button><span v-else>{{row.status==='FULFILLED'?'已履约，不可取消抹账':'无可执行操作'}}</span></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane :label="merchant?'本店应收':'全部应收'" name="receivables"><el-table :data="data.receivables" border><el-table-column prop="id" label="应收号" width="115"/><el-table-column prop="orderId" label="订单号" width="110"/><el-table-column prop="userUid" label="顾客UID" width="140"/><el-table-column v-if="!merchant" prop="merchantUid" label="商家UID" width="125"/><el-table-column label="原始本金" width="120"><template #default="{row}">¥{{money(row.issuedMinor)}}</template></el-table-column><el-table-column label="待还本金" width="120"><template #default="{row}">¥{{money(row.outstandingMinor)}}</template></el-table-column><el-table-column label="应还时间" min-width="180"><template #default="{row}">{{date(row.dueAt)}}<el-tag v-if="row.overdue" type="danger">演示逾期</el-tag></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}">{{labels[row.status]}}</template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane :label="merchant?'本店还款记录':'模拟结果与差异复核'" name="repayments"><el-alert v-if="!merchant" :closable="false" type="info" title="701可控制模拟渠道结果；402可独立复核迟到成功差异。顾客的提交本身不会恢复额度。"/><el-table :data="data.repayments" border style="margin-top:15px"><el-table-column prop="id" label="还款号" width="110"/><el-table-column prop="reference" label="渠道业务号" width="130"/><el-table-column prop="userUid" label="顾客UID" width="140"/><el-table-column prop="merchantUid" label="商家UID" width="125"/><el-table-column label="金额 / 本金分配" min-width="155"><template #default="{row}">拟还 ¥{{money(row.amountMinor)}}<br>核减 ¥{{money(row.allocations.reduce((s,a)=>s+a.amountMinor,0))}}<br><small v-if="row.unallocatedMinor">暂存 / 应退 ¥{{money(row.unallocatedMinor)}}</small></template></el-table-column><el-table-column label="状态" min-width="115"><template #default="{row}"><el-tag :type="row.status==='EXCEPTION'?'danger':row.status==='CONFIRMED'?'success':'info'">{{row.status==='CONFIRMED'?'演示还款已确认':labels[row.status]}}</el-tag><small v-if="row.status==='PENDING'&&row.channelResult==='UNKNOWN'" class="cell-note">结果未知，不当作失败</small></template></el-table-column><el-table-column v-if="!merchant" label="演示控制" min-width="330"><template #default="{row}"><div class="cell-actions" v-if="row.status==='PENDING'"><el-button type="success" :disabled="busy||persona!=='701'" @click="result(row,'CONFIRMED')">演示成功</el-button><el-button :disabled="busy||persona!=='701'" @click="result(row,'TIMEOUT')">结果未知</el-button><el-button type="danger" plain :disabled="busy||persona!=='701'" @click="result(row,'FAILED')">演示失败</el-button><el-button :disabled="busy||persona!=='701'" @click="result(row,'CLOSED')">关闭</el-button></div><el-button v-if="['FAILED','CLOSED'].includes(row.status)" :disabled="busy||persona!=='701'" @click="result(row,'CONFIRMED')">注入迟到成功（演示）</el-button><div v-if="row.status==='EXCEPTION'"><template v-if="!resolutionFor(row)"><el-input v-model="resolutions[row.id]" placeholder="核对依据：事件、金额、商家、剩余本金"/><el-button style="margin-top:8px" :disabled="busy||persona!=='401'||!resolutions[row.id]" @click="action('request-exception-resolution',{repaymentId:row.id,evidence:resolutions[row.id]},'401已提交差异核对申请，等待402独立复核')">401提交复核申请</el-button></template><template v-else><small class="cell-note">申请人 {{resolutionFor(row).creatorId}} · 版本 {{resolutionFor(row).repaymentVersion}}<br>{{resolutionFor(row).evidence}}</small><el-button type="warning" :disabled="busy||persona!=='402'" @click="action('resolve-exception',{resolutionId:resolutionFor(row).id},'402独立复核完成，仅按剩余本金分配')">402独立复核分配</el-button></template></div><el-button v-if="row.status==='CONFIRMED'" :disabled="busy||persona!=='701'" @click="result(row,'CONFIRMED')">重放同一结果验证幂等</el-button></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane v-if="!merchant" label="规则申请与复核" name="rules"><el-alert type="info" :closable="false" :title="'现行演示规则：'+data.rule.code" description="这些参数来自原代码隔离夹具，不代表正式授信。调整须401申请、402独立复核。不得把额度降低到任何用户当前占用以下，旧订单期限等快照不变。"/><el-form class="rule-form" label-width="135px"><el-form-item label="总额度（分）"><el-input-number v-model="ruleForm.quotaMinor" :min="1" :max="1000000" :step="1000"/></el-form-item><el-form-item label="单笔上限（分）"><el-input-number v-model="ruleForm.transactionMaxMinor" :min="1" :max="1000000" :step="100"/></el-form-item><el-form-item label="履约后期限（天）"><el-input-number v-model="ruleForm.termDays" :min="1" :max="365"/></el-form-item><el-form-item label="凭证有效期（秒）"><el-input-number v-model="ruleForm.credentialTtlSeconds" :min="30" :max="600"/></el-form-item><el-form-item label="预占有效期（秒）"><el-input-number v-model="ruleForm.reservationTtlSeconds" :min="60" :max="3600"/></el-form-item><el-form-item><el-button type="primary" :disabled="busy||persona!=='401'" @click="draftRule">401提交演示草稿</el-button><el-button @click="Object.assign(ruleForm,data.rule)">载入现行规则</el-button></el-form-item></el-form><el-table :data="data.ruleDrafts" border><el-table-column prop="id" label="申请号"/><el-table-column prop="creatorId" label="申请人格"/><el-table-column label="候选参数" min-width="240"><template #default="{row}">额度¥{{money(row.rule.quotaMinor)}} / 单笔¥{{money(row.rule.transactionMaxMinor)}} / {{row.rule.termDays}}天</template></el-table-column><el-table-column label="状态"><template #default="{row}">{{labels[row.status]}}</template></el-table-column><el-table-column label="操作" min-width="160"><template #default="{row}"><el-button v-if="row.status==='DRAFT'" type="primary" :disabled="busy||persona!=='402'" @click="action('approve-rule',{ruleId:row.id},'独立复核通过，旧订单快照保持不变')">402独立复核</el-button><span v-else>复核人格 {{row.checkerId}}</span></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="账单异议" name="disputes"><el-table :data="data.disputes" border><el-table-column prop="id" label="异议号"/><el-table-column prop="receivableId" label="应收号"/><el-table-column prop="userUid" label="顾客UID" min-width="145"/><el-table-column prop="reason" label="原因" min-width="240"/><el-table-column prop="status" label="状态"/><el-table-column v-if="!merchant" label="501处理" min-width="300"><template #default="{row}"><template v-if="row.status!=='RESOLVED'"><el-input v-model="resolutions[row.id]" placeholder="填写演示处理说明"/><el-button style="margin-top:8px" :disabled="busy||persona!=='501'||!resolutions[row.id]" @click="action('resolve-dispute',{disputeId:row.id,resolution:resolutions[row.id]},'异议已处理，其他冻结条件仍独立检查')">处理异议</el-button></template><span v-else>{{row.resolution}}</span></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="业务记录" name="events"><el-table :data="data.events" border><el-table-column prop="id" label="记录号" width="110"/><el-table-column prop="type" label="业务事件" min-width="220"/><el-table-column prop="actorId" label="执行人格" width="100"/><el-table-column prop="orderId" label="订单号" width="110"/><el-table-column prop="userUid" label="顾客UID" width="145"/><el-table-column prop="merchantUid" label="商家UID" width="130"/><el-table-column label="金额" width="110"><template #default="{row}">{{row.amountMinor?'¥'+money(row.amountMinor):'—'}}</template></el-table-column><el-table-column label="时间" min-width="190"><template #default="{row}">{{date(row.at)}}</template></el-table-column></el-table></el-tab-pane>
  </el-tabs>
</div>
<div v-else style="padding:30px">正在读取本机先吃后付记录…</div>
</template>
<style scoped>
.credit-workspace{padding:24px;min-width:680px;background:#f6f8fb;min-height:100%}.credit-workspace-header{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:20px}.credit-workspace-header h1{font-size:24px;margin:0 0 8px;color:#25364a}.credit-workspace-header p{font-size:13px;color:#778699;margin:0;line-height:1.7}.credit-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin:22px 0}.credit-stats>div{background:white;border:1px solid #e4e9f0;border-radius:10px;padding:21px}.credit-stats span{font-size:13px;color:#718197}.credit-stats strong{display:block;font-size:28px;color:#253f5c;margin:12px 0}.credit-stats small{font-size:11px;color:#a0acba}.persona-toolbar{display:flex;align-items:center;gap:15px;background:white;padding:14px;border:1px solid #e4e9f0;margin-bottom:20px;border-radius:8px;font-size:13px}.persona-toolbar>span:last-child{font-size:12px;color:#9aa5b3}.credit-workspace h2{font-size:17px;margin:28px 0 16px}.cell-note{display:block;font-size:11px;color:#94a0b0;margin-top:7px}.cell-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.cell-actions .el-button+.el-button{margin:0}.rule-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));padding:24px;background:white;margin:20px 0;border-radius:8px}.credit-workspace :deep(.el-tabs__content){overflow:visible}.credit-workspace :deep(.el-table){font-size:13px}.credit-workspace :deep(.el-tab-pane){background:white;padding:20px;border-radius:8px}@media(max-width:1100px){.credit-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.persona-toolbar{flex-wrap:wrap}}
</style>
