<script setup>
import {computed} from 'vue'
import {useRouter} from 'vue-router'
import {ArrowRight,Connection} from '@element-plus/icons-vue'
import {serviceConnection} from '@/utils/service-mode'
const router=useRouter()
const remote=computed(()=>serviceConnection.mode==='backend')
</script>
<template><main class="integration-page" data-testid="ai-management-overview"><header><span class="integration-eyebrow">平台管理 / AI客服管理</span><h1>AI客服管理</h1><p>配置展示信息，管理顾客与商家的客服会话</p></header><el-alert type="warning" :closable="false" title="外部AI模型未接入" description="配置可保存，会话可由商家或平台手动回复；当前不会请求外部模型，不会自动生成客服回复。"/><section class="integration-grid ai-grid"><button class="integration-channel" @click="router.push('/platform/aiConfiguration')"><div class="integration-channel-top"><span>AI</span><el-tag type="info">配置可保存 · 模型未连接</el-tag></div><h2>AI配置与连接</h2><p>管理模型名称、欢迎语和启用意向；不采集真实API密钥</p><div class="integration-link">打开配置 <ArrowRight/></div></button><button class="integration-channel" @click="router.push('/platform/aiSessions')"><div class="integration-channel-top"><span>聊</span><el-tag :type="remote?'success':'warning'">{{remote?'Java模拟服务':'本机演示'}}</el-tag></div><h2>客服会话与消息</h2><p>按店铺查看顾客消息、手动回复、处理留言和未读记录</p><div class="integration-link">打开客服工作台 <ArrowRight/></div></button></section><section class="integration-panel"><div class="integration-icon"><Connection/></div><div><h2>当前数据范围</h2><p v-if="remote">数据由当前连接的Java模拟服务保存，身份和店铺范围由服务端校验。这里展示的客服消息由用户或工作人员发送，不是AI自动回复。</p><p v-else>当前默认使用本机演示数据，可在本浏览器切换顾客、商家和平台体验会话往返。真实后端地址未配置，不代表跨设备同步。</p><p class="integration-note">切换数据模式需在登录页明确连接Java模拟服务；失败不会改为本机保存成功。真实支付、短信和外部模型仍未启用。</p></div></section></main></template>
<style scoped>.integration-page{padding:28px;max-width:1280px;margin:auto;color:#30445d}.integration-eyebrow{color:#9aa7b6;font-size:12px}.integration-page h1{font-size:26px;margin:10px 0}.integration-page header p{font-size:14px;color:#8a97a8;margin-bottom:24px}.ai-grid{grid-template-columns:repeat(2,1fr)!important}.integration-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:24px}.integration-channel{text-align:left;background:white;border:1px solid #e2e8ef;border-radius:12px;padding:24px;color:inherit;cursor:pointer;transition:box-shadow .15s}.integration-channel:hover{box-shadow:0 8px 24px #253c5910}.integration-channel-top{display:flex;justify-content:space-between;align-items:center}.integration-channel-top>span,.integration-icon{width:46px;height:46px;background:#edf4ff;border-radius:12px;color:#4e83ce;display:flex;align-items:center;justify-content:center;font-size:23px}.integration-page h2{font-size:18px}.integration-page p,.integration-page li{line-height:1.9;font-size:13px}.integration-channel p{color:#8a97a8;min-height:50px}.integration-link{display:flex;align-items:center;justify-content:space-between;color:#6588b9;font-size:13px;margin-top:24px}.integration-link svg{width:15px}.integration-panel{display:flex;gap:24px;border:1px solid #e3e9ef;border-radius:12px;background:white;padding:26px;margin-top:24px}.integration-panel>svg{width:28px;min-width:28px;height:28px;color:#7594b9;margin-top:12px}.integration-icon{flex-shrink:0}.integration-icon svg{width:25px}.integration-panel h2{margin-top:7px}.integration-note{color:#8e9bac;font-size:12px!important}.integration-back{border:0;background:transparent;color:#7191b7;padding:20px 0 0;cursor:pointer}.integration-panel dl{display:grid;grid-template-columns:160px 200px;font-size:13px;row-gap:18px;margin-top:26px}.integration-panel dt{color:#95a0ad}.integration-panel dd{margin:0}@media(max-width:1000px){.integration-grid{grid-template-columns:1fr}}</style>
