<script setup>
import {computed} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {Wallet,Connection,ArrowRight,Warning} from '@element-plus/icons-vue'
const route=useRoute(),router=useRouter()
const channels=[{key:'payWechat',name:'微信支付接入',mark:'微',description:'商户接入、支付下单和通知验签的独立管理入口',fields:['商户主体与应用关联','支付产品与业务场景','异步通知验签和订单对账']},{key:'payBank',name:'银行卡支付接入',mark:'卡',description:'银行或支付机构渠道的独立接入管理入口',fields:['合作银行或支付机构','支持的交易类型与结算方案','通知验证、对账与退款规则']},{key:'payAlipay',name:'支付宝支付接入',mark:'支',description:'应用、商户授权和支付通知的独立管理入口',fields:['应用与商户主体关联','支付产品与授权范围','通知验签、退款与账单核对']}]
const section=computed(()=>route.path.split('/').pop()),isAI=computed(()=>['aiManagement','aiConfiguration','aiSessions'].includes(section.value)),current=computed(()=>channels.find(c=>c.key===section.value))
</script>
<template><main class="integration-page"><header><span class="integration-eyebrow">平台管理 / 后续开发</span><h1>{{isAI?'AI管理系统':current?.name||'系统支付管理'}}</h1><p>{{isAI?'按后续版本中已核实的 AI 配置、连接测试和客服会话模块分组':'将各支付渠道分开配置、开发和验证，当前仅提供管理界面与接入状态概览'}}</p></header><el-alert type="warning" :closable="false" :title="isAI?'尚未接入模型服务':'全部渠道待接入，不能发起真实支付'" :description="isAI?'后续版本含 AI 管理与客服会话模块，本站仅接入管理页面结构，尚未连接对应服务端，不请求外部模型。':'没有配置真实商户信息、支付密钥或证书。先吃后付工作台内的模拟结果与真实支付渠道独立。'"/>
<template v-if="isAI"><section v-if="section==='aiManagement'" class="integration-grid ai-grid"><button class="integration-channel" @click="router.push('/platform/aiConfiguration')"><div class="integration-channel-top"><span>AI</span><el-tag type="info">本站待接入</el-tag></div><h2>AI配置与连接</h2><p>原版本包含启停、模型选择、欢迎语、配置保存及连接测试</p><div class="integration-link">查看配置概览 <ArrowRight/></div></button><button class="integration-channel" @click="router.push('/platform/aiSessions')"><div class="integration-channel-top"><span>聊</span><el-tag type="info">本站待接入</el-tag></div><h2>客服会话与消息</h2><p>原版本包含客服会话列表、按会话查看消息详情</p><div class="integration-link">查看会话管理 <ArrowRight/></div></button></section>
<button v-else class="integration-back" @click="router.push('/platform/aiManagement')">‹ 返回AI管理系统</button>
<section class="integration-panel"><div class="integration-icon"><Connection/></div><div><el-tag type="success">源码模块已核实</el-tag><h2>{{section==='aiConfiguration'?'AI配置与连接概览':section==='aiSessions'?'客服会话与消息管理':'AI功能接入与开发区'}}</h2><template v-if="section==='aiSessions'"><p>后续版本已有会话列表与消息详情功能。本站未连接会话后端，当前无法读取实际会话，不显示伪造记录。</p><ul><li>会话列表：待接入</li><li>消息详情：待接入</li><li>数据权限与隐私校验：待服务端集成</li></ul></template><template v-else><p>后续版本已有 AI 配置和连接测试页面；本站尚未配置模型或接通接口。</p><ul><li>AI启用状态：未启用</li><li>模型供应商与模型：未配置</li><li>欢迎语与配置保存：待服务端接入</li><li>连接测试与用量：尚未启用</li></ul></template><p class="integration-note">此处不收集 API key，不提供虚假的启用开关。当前没有可执行的 AI 请求。</p></div></section></template>
<template v-else-if="!current"><section class="integration-grid"><button v-for="channel in channels" :key="channel.key" class="integration-channel" @click="router.push('/platform/'+channel.key)"><div class="integration-channel-top"><span>{{channel.mark}}</span><el-tag type="info">待接入</el-tag></div><h2>{{channel.name}}</h2><p>{{channel.description}}</p><div class="integration-link">查看接入管理 <ArrowRight/></div></button></section><section class="integration-panel"><Wallet/><div><h2>统一接入状态</h2><p>已接入 0 / 3 个渠道。当前订单、还款与退款的演示记录不会发送给微信、银行或支付宝。</p></div></section></template>
<template v-else><button class="integration-back" @click="router.push('/platform/paymentManagement')">‹ 返回系统支付管理</button><section class="integration-panel"><div class="integration-icon">{{current.mark}}</div><div><el-tag type="info">待接入 · 未启用</el-tag><h2>{{current.name}}</h2><p>{{current.description}}</p><dl><dt>商户/机构配置</dt><dd>未配置</dd><dt>接口连通状态</dt><dd>未测试</dd><dt>回调与验签</dt><dd>未开发</dd><dt>真实交易</dt><dd>不可用</dd></dl></div></section><section class="integration-panel"><Warning/><div><h2>后续开发范围</h2><ol><li v-for="field in current.fields" :key="field">{{field}}</li></ol><p class="integration-note">正式接入需要服务器安全保存敏感配置、服务端鉴权与可靠账务处理。此页面不会采集、保存支付密钥、银行卡号或证书，也不会发出支付请求。</p></div></section></template>
</main></template>
<style scoped>.integration-page{padding:28px;max-width:1280px;margin:auto;color:#30445d}.integration-eyebrow{color:#9aa7b6;font-size:12px}.integration-page h1{font-size:26px;margin:10px 0}.integration-page header p{font-size:14px;color:#8a97a8;margin-bottom:24px}.ai-grid{grid-template-columns:repeat(2,1fr)!important}.integration-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:24px}.integration-channel{text-align:left;background:white;border:1px solid #e2e8ef;border-radius:12px;padding:24px;color:inherit;cursor:pointer;transition:box-shadow .15s}.integration-channel:hover{box-shadow:0 8px 24px #253c5910}.integration-channel-top{display:flex;justify-content:space-between;align-items:center}.integration-channel-top>span,.integration-icon{width:46px;height:46px;background:#edf4ff;border-radius:12px;color:#4e83ce;display:flex;align-items:center;justify-content:center;font-size:23px}.integration-page h2{font-size:18px}.integration-page p,.integration-page li{line-height:1.9;font-size:13px}.integration-channel p{color:#8a97a8;min-height:50px}.integration-link{display:flex;align-items:center;justify-content:space-between;color:#6588b9;font-size:13px;margin-top:24px}.integration-link svg{width:15px}.integration-panel{display:flex;gap:24px;border:1px solid #e3e9ef;border-radius:12px;background:white;padding:26px;margin-top:24px}.integration-panel>svg{width:28px;min-width:28px;height:28px;color:#7594b9;margin-top:12px}.integration-icon{flex-shrink:0}.integration-icon svg{width:25px}.integration-panel h2{margin-top:7px}.integration-note{color:#8e9bac;font-size:12px!important}.integration-back{border:0;background:transparent;color:#7191b7;padding:20px 0 0;cursor:pointer}.integration-panel dl{display:grid;grid-template-columns:160px 200px;font-size:13px;row-gap:18px;margin-top:26px}.integration-panel dt{color:#95a0ad}.integration-panel dd{margin:0}@media(max-width:1000px){.integration-grid{grid-template-columns:1fr}}</style>
