<script setup>
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { User, Shop, Setting, ArrowLeft } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import request,{demoStores} from '@/utils/request'
import BackendConnectionForm from '@/components/BackendConnectionForm.vue'
import {useDemoMode,serviceConnection} from '@/utils/service-mode'
const router=useRouter(),route=useRoute()
const backendOpen=ref(serviceConnection.mode==='backend')
function backendConnected(context){const r=context.actor.role,target=String(route.query.returnTo||'');const allowed=r==='ROLE_ADMIN'?target.startsWith('/platform/'):r==='ROLE_UNIT'?target.startsWith('/merchant/'):target.startsWith('/mall/');router.push(allowed&&!target.includes('://')?target:r==='ROLE_ADMIN'?'/platform/support':r==='ROLE_UNIT'?'/merchant/support':'/mall/support')}
const role=ref('ROLE_USER'),username=ref('111'),password=ref('111'),busy=ref(false)
const demoStoreRows=ref([]),demoStoreId=ref('')
onMounted(()=>{demoStoreRows.value=demoStores();demoStoreId.value=demoStoreRows.value[0]?.id||''})
const roles=[{id:'ROLE_USER',label:'顾客',desc:'逛商家、选餐品、先吃后付',icon:User},{id:'ROLE_UNIT',label:'商家',desc:'本店订单、核销与应收',icon:Shop},{id:'ROLE_ADMIN',label:'平台',desc:'平台管理与业务复核',icon:Setting}]
async function login(){if(busy.value)return;busy.value=true;try{useDemoMode();const r=await request.post('/web/login',{username:username.value,password:password.value,role:role.value,...(role.value==='ROLE_UNIT'?{unitId:Number(demoStoreId.value)}:{})});if(r.code!=='200')return ElMessage.error(r.msg);sessionStorage.setItem('account',JSON.stringify(r.data));const target=String(route.query.returnTo||'');router.push(role.value==='ROLE_USER'?(target.startsWith('/mall/')&&!target.includes('://')?target:'/mall/home'):role.value==='ROLE_UNIT'?'/merchant/credit':'/platform/credit')}finally{busy.value=false}}
</script>
<template><div class="native-stage entry-stage"><div class="native-device"><main class="native-app entry-app"><header class="native-header"><button @click="router.push('/mall/home')" aria-label="返回商城"><ArrowLeft/></button><strong>选择体验身份</strong><img class="app-brand-icon" src="/brand/dining-logo-v5.svg" alt="鲜食好店标志"/></header><section class="entry-content"><img class="entry-logo" src="/brand/dining-app-icon-v5.svg" alt="鲜食好店应用标志"/><h1>鲜食好店</h1><p>好好吃饭，轻松体验</p><BackendConnectionForm v-if="backendOpen" @connected="backendConnected" @demo="backendOpen=false"/><template v-else><div class="entry-roles"><button v-for="item in roles" :key="item.id" :class="{selected:role===item.id}" @click="role=item.id"><component :is="item.icon"/><strong>{{item.label}}</strong></button></div><p class="entry-role-desc">{{roles.find(r=>r.id===role).desc}}</p><form class="native-form" @submit.prevent="login"><label v-if="role==='ROLE_UNIT'">选择示例店铺<select v-model="demoStoreId" aria-label="商家体验店铺" required><option v-for="store in demoStoreRows" :key="store.id" :value="store.id">{{store.nickname}}</option></select><small>本机演示，每家店铺只查看自己的业务记录</small></label><label>体验账号<input v-model="username" aria-label="体验账号" autocomplete="off" placeholder="111" required/></label><label>体验密码<input v-model="password" aria-label="体验密码" type="password" autocomplete="off" placeholder="111" required/></label><button class="primary-pill full" type="submit" :disabled="busy">{{busy?'正在进入':'进入'+roles.find(r=>r.id===role).label+'端'}}</button></form><p class="entry-tip">三种身份均使用 111 / 111<br>仅演示业务，未接真实身份认证或资金支付</p><button class="entry-guest" @click="router.push('/mall/home')">先逛逛商城</button><button class="entry-guest" @click="backendOpen=true">连接Java模拟服务</button></template></section></main></div></div></template>
<style scoped>.entry-content{padding:22px 28px 40px;text-align:center}.entry-logo{display:grid;place-items:center;width:64px;height:64px;background:linear-gradient(135deg,#ff7830,#ff4224);color:white;border-radius:20px;font-size:31px;font-weight:600;margin:8px auto 18px}.entry-content h1{font-size:25px;margin:0 0 7px}.entry-content>p{font-size:12px;color:#aaa}.entry-roles{display:flex;gap:10px;margin:32px 0 13px}.entry-roles button{display:flex;flex:1;flex-direction:column;gap:10px;align-items:center;border:1px solid #e6e6e6;border-radius:9px;padding:15px 5px;color:#888;background:white}.entry-roles button.selected{border-color:#ff825f;background:#fff5f0;color:#ff582e}.entry-roles strong{font-size:13px;font-weight:500}.entry-role-desc{color:#bf724c!important}.native-form{text-align:left;margin-top:25px}.native-form label{font-size:12px;color:#777}.entry-tip{line-height:1.8;margin-top:24px!important;font-size:11px!important}.entry-guest{font-size:12px!important;color:#b27353!important;margin-top:18px}.entry-app{background:#fff9f5}.native-form select{width:100%;padding:11px;border:1px solid #e6e6e6;border-radius:6px;background:#fff;font-size:12px;color:#777}.native-form label>small{display:block;font-size:9px;color:#aaa;margin-top:6px}</style>
