package cn.iocoder.yudao.server.simulation;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import java.util.*;
import static cn.iocoder.yudao.server.simulation.SimContext.*;
import static org.junit.jupiter.api.Assertions.*;

class ShopSupportTest {
    static class Fixture extends EngineContractTest.F {
        String platform;
        void ready(){setup();platform=login("SIM-SUPPORT-001");clock.tick(61);}
        Map<String,Object> action(String suffix,String token,Map<String,Object> body){Map<String,Object> result=data("POST","/api/v1/support/"+suffix,token,body);return bool(result,"detailRequired")?query("ticket",token,"id",s(result,"id")):result;}
        Map<String,Object> query(String suffix,String token,String... pairs){Map<String,String> p=new LinkedHashMap<>();for(int i=0;i<pairs.length;i+=2)p.put(pairs[i],pairs[i+1]);return (Map<String,Object>)req("GET","/api/v1/support/"+suffix,token,map(),"unused-get-key-0001",p).get("data");}
        Map<String,Object> open(){return action("open-session",user,map("unitId",storeId));}
        Map<String,Object> ticket(){return action("create-ticket",user,map("unitId",storeId,"title","等待答复","content","请核实模拟订单","priority","HIGH"));}
        void clerkOtherShop(){SimContext c=new SimContext(store.state,"201",clock.instant());Map<String,Object> second=c.create("stores",map("merchantUid",merchant,"name","另一门店","active",true));c.create("grants",map("userId","202","role","CLERK","merchantUid",merchant,"storeId",s(second,"id"),"status","ACTIVE"));}
    }
    static List<Map<String,Object>> rows(Map<String,Object> m,String key){return (List<Map<String,Object>>)m.get(key);}
    static void failure(int status,Runnable call){SimException e=assertThrows(SimException.class,call::run);assertEquals(status,e.status,e.code+": "+e.getMessage());}
    @Test void contextAndScopeComeFromAuthenticatedServerIdentity(){Fixture f=new Fixture();f.ready();Map<String,Object> view=f.query("context",f.user);assertEquals("101",s((Map)view.get("actor"),"id"));assertEquals("ROLE_USER",s((Map)view.get("actor"),"role"));assertEquals(f.storeId,s(rows(view,"shops").get(0),"unitId"));assertEquals("ROLE_UNIT",s((Map)f.query("context",f.owner).get("actor"),"role"));assertEquals("ROLE_ADMIN",s((Map)f.query("context",f.platform).get("actor"),"role"));failure(401,()->f.query("context",null));}
    @Test void cannotSpoofCustomerSenderOrUnknownQuery(){Fixture f=new Fixture();f.ready();failure(422,()->f.action("open-session",f.user,map("unitId",f.storeId,"userId","102")));Map<String,Object> ss=f.open();failure(422,()->f.action("send-message",f.user,map("sessionId",s(ss,"id"),"text","x","senderId","501")));failure(422,()->f.query("overview",f.user,"userId","102"));failure(403,()->f.action("open-session",f.owner,map("unitId",f.storeId)));}
    @Test void sessionsReuseAndIdempotentSendCannotDuplicate(){Fixture f=new Fixture();f.ready();Map<String,Object> ss=f.open();assertEquals(s(ss,"id"),s(f.open(),"id"));Map<String,Object> b=map("sessionId",s(ss,"id"),"text","请问营业时间？");Map a=f.req("POST","/api/v1/support/send-message",f.user,b,"stable-support-message-key",new LinkedHashMap<>()),again=f.req("POST","/api/v1/support/send-message",f.user,b,"stable-support-message-key",new LinkedHashMap<>());assertEquals(new ObjectMapper().valueToTree(a).toString(),new ObjectMapper().valueToTree(again).toString());assertEquals(1,f.store.state.table("supportMessages").size());failure(409,()->f.req("POST","/api/v1/support/send-message",f.user,map("sessionId",s(ss,"id"),"text","changed"),"stable-support-message-key",new LinkedHashMap<>()));}
    @Test void crossCustomerAndCrossStoreCannotReadOrReply(){Fixture f=new Fixture();f.ready();f.clerkOtherShop();String clerk=f.login("SIM-CLERK-001");Map<String,Object> ss=f.open(),ticket=f.ticket();for(String token:Arrays.asList(f.other,clerk)){failure(404,()->f.query("session",token,"id",s(ss,"id")));failure(404,()->f.query("ticket",token,"id",s(ticket,"id")));failure(404,()->f.action("send-message",token,map("sessionId",s(ss,"id"),"text","unwanted")));assertTrue(rows(f.query("overview",token),"tickets").isEmpty());}assertEquals(1,rows(f.query("overview",f.owner),"tickets").size());}
    @Test void readCursorClearsOnlySeenMessagesAndNeverMutatesOnGet(){Fixture f=new Fixture();f.ready();Map<String,Object> ss=f.open();String id=s(ss,"id");Map<String,Object> first=f.action("send-message",f.user,map("sessionId",id,"text","first"));f.action("send-message",f.user,map("sessionId",id,"text","arrived later"));assertEquals(2,n((Map)f.query("session",f.owner,"id",id).get("session"),"unread"));assertEquals(2,n((Map)f.query("session",f.owner,"id",id).get("session"),"unread"));Map<String,Object> seen=f.action("mark-read",f.owner,map("sessionId",id,"lastSeenMessageId",s(first,"id")));assertEquals(1,n(seen,"unread"));assertEquals(0,n((Map)f.query("session",f.user,"id",id).get("session"),"unread"));Map<String,Object> other=f.action("open-session",f.other,map("unitId",f.storeId));Map<String,Object> foreign=f.action("send-message",f.other,map("sessionId",s(other,"id"),"text","other thread"));failure(404,()->f.action("mark-read",f.user,map("sessionId",id,"lastSeenMessageId",s(foreign,"id"))));}
    @Test void ticketWorkflowIsVersionedMultiReplyAndCanReopen(){Fixture f=new Fixture();f.ready();Map<String,Object> t=f.ticket();String id=s(t,"id");failure(409,()->f.action("ticket-status",f.user,map("ticketId",id,"version",1,"status","RESOLVED")));t=f.action("reply-ticket",f.owner,map("ticketId",id,"version",1,"text","第一轮"));failure(409,()->f.action("reply-ticket",f.platform,map("ticketId",id,"version",1,"text","过期覆盖")));t=f.action("reply-ticket",f.user,map("ticketId",id,"version",2,"text","补充情况"));assertEquals(2,rows(t,"replies").size());for(String status:Arrays.asList("IN_PROGRESS","RESOLVED"))t=f.action("ticket-status",f.owner,map("ticketId",id,"version",n(t,"version"),"status",status));t=f.action("ticket-status",f.user,map("ticketId",id,"version",n(t,"version"),"status","CLOSED"));long closedVersion=n(t,"version");failure(409,()->f.action("reply-ticket",f.owner,map("ticketId",id,"version",closedVersion,"text","不可回复")));t=f.action("ticket-status",f.user,map("ticketId",id,"version",closedVersion,"status","OPEN"));assertEquals("OPEN",s(t,"status"));assertEquals(7,rows(t,"history").size());}
    @Test void ownerArchiveKeepsHistoryButRevokesMerchantIncludingIdempotentReplay(){Fixture f=new Fixture();f.ready();Map<String,Object> t=f.ticket();String id=s(t,"id");Map<String,Object> body=map("ticketId",id,"version",1,"text","商家回复");f.req("POST","/api/v1/support/reply-ticket",f.owner,body,"archive-replay-original-key",new LinkedHashMap<>());failure(403,()->f.action("archive-ticket",f.owner,map("ticketId",id,"version",2,"reason","商家不能归档")));t=f.action("archive-ticket",f.user,map("ticketId",id,"version",2,"reason","本人收起"));assertTrue(bool(t,"archived"));failure(404,()->f.query("ticket",f.owner,"id",id));failure(404,()->f.req("POST","/api/v1/support/reply-ticket",f.owner,body,"archive-replay-original-key",new LinkedHashMap<>()));assertTrue(rows(f.query("overview",f.user),"tickets").isEmpty());assertEquals(1,rows(f.query("overview",f.user,"includeArchived","true"),"tickets").size());assertEquals(1,rows(f.query("overview",f.platform,"includeArchived","true"),"tickets").size());t=f.action("restore-ticket",f.user,map("ticketId",id,"version",3,"reason","继续处理"));assertFalse(bool(t,"archived"));assertEquals(4,rows(t,"history").size());assertEquals("商家回复",s(rows(t,"replies").get(0),"text"));}
    @Test void titlePriorityPaginationAndOrderOwnershipAreValidated(){Fixture f=new Fixture();f.ready();String title=String.join("",Collections.nCopies(200,"题"));Map<String,Object> t=f.action("create-ticket",f.user,map("unitId",f.storeId,"title",title,"content","正文","priority","IMPORTANT"));assertEquals("HIGH",s(t,"priority"));failure(422,()->f.action("create-ticket",f.user,map("unitId",f.storeId,"title",title+"超","content","正文","priority","MEDIUM")));failure(422,()->f.query("overview",f.user,"limit","11"));assertEquals(1,rows(f.query("overview",f.user,"priority","HIGH","limit","10","page","1"),"tickets").size());assertTrue(rows(f.query("overview",f.user,"page","2"),"tickets").isEmpty());Map<String,Object> order=f.data("POST","/api/v1/orders",f.owner,map("storeId",f.storeId,"items",Arrays.asList(map("productId",f.productId,"quantity",1,"productVersion",1)),"clientReference","support-unowned-order"));failure(403,()->f.action("create-ticket",f.user,map("unitId",f.storeId,"title","x","content","x","priority","MEDIUM","orderId",s(order,"id"))));}
    @Test void supportDoesNotChangeFinancialStateAndSurvivesRoundtrip()throws Exception{Fixture f=new Fixture();f.ready();f.fulfill();ObjectMapper json=new ObjectMapper();Map<String,Object> before=new LinkedHashMap<>();for(String kind:Arrays.asList("orders","accounts","receivables","journals","lines","refunds","repayments"))before.put(kind,json.writeValueAsString(f.store.state.table(kind)));Map<String,Object> ss=f.open(),t=f.ticket();f.action("send-message",f.user,map("sessionId",s(ss,"id"),"text","只咨询"));f.action("reply-ticket",f.owner,map("ticketId",s(t,"id"),"version",1,"text","已查看"));for(String kind:before.keySet())assertEquals(before.get(kind),json.writeValueAsString(f.store.state.table(kind)),kind);SimState restored=json.readValue(json.writeValueAsBytes(f.store.state),SimState.class);SimulationEngine restart=new SimulationEngine(new EngineContractTest.Memory(){ {state=restored;} },f.clock);Map response=(Map)restart.request("GET","/api/v1/support/ticket",map(),new LinkedHashMap<>(Collections.singletonMap("id",s(t,"id"))),new LinkedHashMap<>(Collections.singletonMap("authorization",f.user)),new byte[0],"restart-test");assertEquals(1,rows((Map)response.get("data"),"replies").size());}
    @Test void ticketMutationAndOverviewAvoidDuplicatingFullHistoryInIdempotency(){Fixture f=new Fixture();f.ready();Map<String,Object> t=f.ticket();String id=s(t,"id");Map<String,Object> response=f.data("POST","/api/v1/support/reply-ticket",f.owner,map("ticketId",id,"version",1,"text","summary only"));assertTrue(bool(response,"detailRequired"));assertFalse(response.containsKey("history"));assertFalse(response.containsKey("replies"));assertEquals(1,n(response,"replyCount"));assertEquals(2,n(response,"historyCount"));Map<String,Object> row=rows(f.query("overview",f.owner),"tickets").get(0);assertFalse(row.containsKey("history"));assertFalse(row.containsKey("replies"));assertEquals(1,n(row,"replyCount"));Map<String,Object> detail=f.query("ticket",f.owner,"id",id);assertEquals(1,rows(detail,"replies").size());assertEquals(2,rows(detail,"history").size());for(Map<String,Object> cached:f.store.state.table("idempotency").values())if("support.reply".equals(s(cached,"operationId"))){Map data=(Map)((Map)cached.get("response")).get("data");assertFalse(data.containsKey("history"));assertFalse(data.containsKey("replies"));}}
    @Test void unknownFutureSchemaFailsClosedWithoutReplacingStoredVersion(){Fixture f=new Fixture();f.ready();f.store.state.meta.put("supportSchemaVersion",2);failure(503,()->f.query("overview",f.user));failure(503,()->f.open());assertEquals(2,n(f.store.state.meta,"supportSchemaVersion"));f.store.state.meta.put("supportSchemaVersion",1.5);failure(503,()->f.query("profile",f.user));}
    @Test void immutableMessageReplyAndHistoryEvidenceCannotBeRewritten()throws Exception{Fixture f=new Fixture();f.ready();Map<String,Object> ss=f.open(),t=f.ticket();f.action("send-message",f.user,map("sessionId",s(ss,"id"),"text","消息"));f.action("reply-ticket",f.owner,map("ticketId",s(t,"id"),"version",1,"text","回复"));ObjectMapper mapper=new ObjectMapper();for(String kind:Arrays.asList("supportMessages","supportTicketReplies","supportTicketHistory")){SimState changed=mapper.readValue(mapper.writeValueAsBytes(f.store.state),SimState.class);changed.table(kind).values().iterator().next().put("text","tampered");assertThrows(IllegalStateException.class,()->JdbcSimStore.assertAppendOnly(f.store.state,changed));}}
}
