<script setup>
import {ref,computed,watch,onUnmounted} from 'vue'
import {Document,Download,Warning} from '@element-plus/icons-vue'
import request from '@/utils/request'
import {base64Blob,fileKind} from '@/utils/service-files'
import {serviceConnection} from '@/utils/service-mode'
const props=defineProps({attachment:{type:Object,required:true},compact:Boolean})
const url=ref(''),error=ref(''),loading=ref(false),expanded=ref(false),details=ref(null);let version=0,disposed=false
const kind=computed(()=>fileKind(props.attachment.mime||props.attachment.type||''))
function release(){if(url.value.startsWith('blob:'))URL.revokeObjectURL(url.value);url.value=''}
async function load(force=false){if(loading.value||url.value&&!force)return;const current=++version;loading.value=true;error.value='';try{let data;if(props.attachment.dataUrl&&/^data:image\/(png|jpeg|gif|webp);base64,/.test(props.attachment.dataUrl)){data={...props.attachment,mime:props.attachment.mime||props.attachment.dataUrl.slice(5).split(';')[0],base64:props.attachment.dataUrl.split(',')[1]}}else{const r=await request.get('/support/attachments/download',{params:{id:props.attachment.id}});if(r.code!=='200')throw Error(r.msg);data=r.data}const blob=base64Blob(data);if(disposed||current!==version)return;release();url.value=URL.createObjectURL(blob);details.value=data}catch(e){if(!disposed&&current===version)error.value=e.message}finally{if(!disposed&&current===version)loading.value=false}}
async function download(){await load();if(!url.value)return;const link=document.createElement('a');link.href=url.value;link.download=details.value?.name||props.attachment.name||'附件';document.body.appendChild(link);link.click();link.remove()}
watch(()=>[props.attachment.id,props.attachment.dataUrl,serviceConnection.revision],()=>{version++;release();details.value=null;loading.value=false;error.value='';expanded.value=false;if(kind.value==='image')load()},{immediate:true})
onUnmounted(()=>{disposed=true;version++;release()})
</script>
<template><div class="service-attachment" :class="{compact}" :data-attachment-id="attachment.id" data-testid="service-attachment"><template v-if="kind==='image'"><img v-if="url" :src="url" :alt="attachment.name" :class="{expanded}" @click="expanded=!expanded"/><button v-else type="button" @click="load">{{loading?'正在读取图片':'查看图片'}}</button></template><template v-else-if="kind==='video'"><video v-if="url" :src="url" controls playsinline preload="metadata"></video><button v-else type="button" @click="load">{{loading?'正在读取视频':'加载视频预览'}}</button></template><div class="attachment-caption"><Document v-if="kind==='file'"/><span>{{attachment.name}}<small>{{attachment.mime||'图片'}} · {{Math.ceil((attachment.size||0)/1024)}} KiB</small></span><button type="button" :disabled="loading" aria-label="下载附件" @click="download"><Download/></button></div><small class="attachment-scan"><Warning/>未经安全扫描，请仅打开可信来源文件</small><p v-if="error" role="alert" class="attachment-error">{{error}} <button type="button" @click="load(true)">重试</button></p></div></template>
<style scoped>.service-attachment{border:1px solid #e8dfd8;background:#fff;border-radius:8px;padding:9px;margin:7px 0;max-width:100%;overflow:hidden}.service-attachment>img{display:block;max-width:100%;max-height:150px;object-fit:contain;cursor:zoom-in;margin:auto}.service-attachment>img.expanded{max-height:65vh;cursor:zoom-out}.service-attachment>video{display:block;width:100%;max-height:260px}.service-attachment>button{padding:9px!important;color:#aa7854!important;font-size:13px!important}.attachment-caption{display:flex;align-items:center;gap:8px;margin-top:8px}.attachment-caption>svg{width:20px!important;height:20px!important;color:#b19883;flex-shrink:0}.attachment-caption>span{flex:1;min-width:0;overflow-wrap:anywhere;font-size:12px;line-height:1.6}.attachment-caption small{display:block;font-size:10px;color:#aaa}.attachment-caption button{padding:5px!important;color:#a57956!important;background:transparent;border:0;cursor:pointer}.attachment-caption button svg{width:17px!important;height:17px!important}.attachment-scan{display:flex;align-items:flex-start;gap:4px;color:#a28e7e;font-size:10px;line-height:1.6;margin-top:8px}.attachment-scan svg{width:12px!important;height:12px!important;flex-shrink:0;margin-top:2px}.attachment-error{font-size:12px!important;color:#c7704e!important;line-height:1.6}.attachment-error button{border:0;background:none;text-decoration:underline;color:inherit}.compact{padding:7px}.compact .attachment-caption{font-size:11px}</style>
