<script setup>
import {ref,onUnmounted,watch} from 'vue'
import {Paperclip,Close} from '@element-plus/icons-vue'
import {ElMessage} from 'element-plus'
import request from '@/utils/request'
import {readServiceFile,SERVICE_FILE_TYPES,SERVICE_COMMAND_LIMIT,serviceKey} from '@/utils/service-files'
import {serviceConnection} from '@/utils/service-mode'
const props=defineProps({modelValue:{type:Array,default:()=>[]},disabled:Boolean,contextKey:String})
const emit=defineEmits(['update:modelValue','busy'])
const busy=ref(false),error=ref('');let version=0,disposed=false
function reset(){version++;busy.value=false;emit('busy',false);error.value=''}
async function select(event){const files=[...(event.target.files||[])];event.target.value='';if(!files.length||props.disabled||busy.value)return;if(props.modelValue.length+files.length>5)return ElMessage.warning('每次最多5个附件');if(props.modelValue.reduce((s,f)=>s+Number(f.size||0),0)+files.reduce((s,f)=>s+f.size,0)>SERVICE_COMMAND_LIMIT)return ElMessage.warning('一次提交的附件总量不能超过1 MiB');const stamp=++version,currentContext=props.contextKey,connection=serviceConnection.revision;busy.value=true;emit('busy',true);error.value='';let selected=[...props.modelValue];try{for(const file of files){const body=await readServiceFile(file);if(disposed||stamp!==version||currentContext!==props.contextKey||connection!==serviceConnection.revision)return;const r=await request.post('/support/attachments/upload',{...body,clientKey:serviceKey('UPLOAD')});if(disposed||stamp!==version||currentContext!==props.contextKey||connection!==serviceConnection.revision)return;if(r.code!=='200')throw Error(r.msg);selected.push(r.data);emit('update:modelValue',[...selected])}}catch(e){if(!disposed&&stamp===version)error.value=e.message}finally{if(!disposed&&stamp===version){busy.value=false;emit('busy',false)}}}
function remove(id){if(busy.value||props.disabled)return;emit('update:modelValue',props.modelValue.filter(a=>a.id!==id))}
watch(()=>[props.contextKey,serviceConnection.revision],reset)
onUnmounted(()=>{disposed=true;reset()})
</script>
<template><div class="service-upload" data-testid="service-upload"><label class="service-upload-button" :class="{disabled:disabled||busy}"><Paperclip/><span>{{busy?'正在保存附件':'添加图片 / 文件 / 视频'}}</span><input type="file" multiple :accept="SERVICE_FILE_TYPES.join(',')" :disabled="disabled||busy" aria-label="选择服务附件" data-testid="service-upload-input" @change="select"/></label><div v-for="a in modelValue" :key="a.id" class="upload-file-row"><span>{{a.name}}<small>{{Math.ceil(a.size/1024)}} KiB · {{a.mime}}</small></span><button type="button" :disabled="disabled||busy" aria-label="移除待提交附件" @click="remove(a.id)"><Close/></button></div><small class="upload-limits">最多5个；单个512 KiB、合计1 MiB。支持常见图片、PDF、TXT、MP4；未经安全扫描。</small><p v-if="error" role="alert">{{error}}</p></div></template>
<style scoped>.service-upload{margin:10px 0;text-align:left;max-width:100%}.service-upload-button{position:relative;display:flex;align-items:center;gap:7px;font-size:13px;color:#a87c5c;padding:10px 12px;border:1px dashed #dccabc;border-radius:7px;background:#fffaf7;cursor:pointer}.service-upload-button svg{width:17px!important;height:17px!important}.service-upload-button input{position:absolute;inset:0;opacity:0;width:100%;cursor:pointer}.service-upload-button.disabled{opacity:.55;cursor:default}.upload-file-row{display:flex;align-items:center;gap:10px;padding:8px 10px;background:#faf8f6;margin-top:6px;border-radius:5px}.upload-file-row span{flex:1;font-size:12px;overflow-wrap:anywhere;min-width:0}.upload-file-row small{display:block;font-size:10px;color:#aaa;margin-top:4px}.upload-file-row button{border:0;background:none;color:#aaa;cursor:pointer;padding:3px}.upload-file-row svg{width:15px!important;height:15px!important}.upload-limits{display:block;font-size:10px;color:#aa9a8e;line-height:1.7;margin-top:8px}.service-upload>p{font-size:12px;color:#c8744f;line-height:1.6}</style>
