import test from 'node:test'
import assert from 'node:assert/strict'
import {createClient,unwrap,requestKey,safePath,parseMinor,money,redact,ApiError,errorHint} from '../src/api.js'
const reply=(data,status=200)=>({ok:status<400,status,json:async()=>data})
test('supports both envelopes and raw simulation resources',()=>{assert.deepEqual(unwrap({data:{id:'9223372036854775807'},meta:{}}),{id:'9223372036854775807'});assert.deepEqual(unwrap({code:0,data:{days:[]}}),{days:[]});assert.deepEqual(unwrap({resources:{}}),{resources:{}});assert.throws(()=>unwrap({code:'DENIED',message:'拒绝'}),ApiError)})
test('opaque identifiers survive substitution; monetary values are integer cents',()=>{assert.equal(safePath('/api/v1/orders/{id}',{id:'9223372036854775807'}),'/api/v1/orders/9223372036854775807');assert.equal(safePath('/api/v1/orders/{id}',{id:'a/b'}),'/api/v1/orders/a%2Fb');assert.throws(()=>safePath('/x/{id}',{}));assert.equal(parseMinor('8800'),8800);for(const v of ['88.2','0','-1','1e3','9007199254740993'])assert.throws(()=>parseMinor(v));assert.equal(money(undefined),'未读取');assert.equal(money(0),'¥0.00')})
test('duplicate clicks share one in-flight network request',async()=>{let calls=0,finish;const client=createClient({fetchImpl:()=>{calls++;return new Promise(r=>finish=r)}});const key=requestKey();assert.ok(key.length>=16&&key.length<=128);const a=client.once(key,'/api/v1/orders',{method:'POST',body:{id:'12'},key}),b=client.once(key,'/api/v1/orders',{method:'POST',body:{id:'12'},key});assert.equal(a,b);finish(reply({data:{id:'12'}}));await a;assert.equal(calls,1)})
test('retry preserves idempotency key and body across unknown network outcome',async()=>{const calls=[];const client=createClient({fetchImpl:async(url,opt)=>{calls.push(opt);if(calls.length===1)throw new TypeError('Network error');return reply({data:{id:'1'}})}});const command={method:'POST',body:{amountMinor:900},token:'memory-test-token',key:requestKey()};await assert.rejects(client.request('/api/v1/repayments',command),e=>e.retryable);await client.request('/api/v1/repayments',command);assert.equal(calls[0].headers['Idempotency-Key'],calls[1].headers['Idempotency-Key']);assert.equal(calls[0].body,calls[1].body);assert.equal(calls[1].headers.Authorization,'Bearer memory-test-token')})
test('version conflict is not auto retryable and requests refresh',async()=>{const client=createClient({fetchImpl:async()=>reply({code:'VERSION_CONFLICT',message:'已改变',requestId:'req-x'},409)});await assert.rejects(client.request('/api/v1/orders/1',{method:'POST'}),e=>{assert.equal(e.retryable,false);assert.equal(e.requestId,'req-x');assert.match(errorHint(e),/刷新/);return true})})
test('client never sends bearer token to an external or protocol-relative destination',async()=>{let called=false;const client=createClient({fetchImpl:async()=>{called=true}});for(const path of ['https://evil.example/api/v1/orders','//evil.example/api/v1/orders','/admin-api/test'])await assert.rejects(client.request(path,{token:'secret'}));assert.equal(called,false)})
test('activity records remove tokens, one-time credentials and signatures',()=>{assert.deepEqual(redact({accessToken:'a',refreshToken:'b',nested:{credential:'c',signature:'s',id:'8'},amountMinor:100}),{accessToken:'[仅内存保留]',refreshToken:'[仅内存保留]',nested:{credential:'[仅内存保留]',signature:'[仅内存保留]',id:'8'},amountMinor:100})})
test('authenticated download uses fetch header and returns blob',async()=>{let headers;const blob=new Blob(['csv']);const client=createClient({fetchImpl:async(_,opt)=>{headers=opt.headers;return {ok:true,status:200,blob:async()=>blob}}});const r=await client.request('/api/v1/exports/1/content?token=test',{token:'session',binary:true});assert.equal(r.data,blob);assert.equal(headers.Authorization,'Bearer session')})
