import assert from 'node:assert/strict'
import fs from 'node:fs'
import {publicReviews,submitReview,replyReview,createAfterSales,merchantAfterSales,feedbackOrders} from '../src/utils/feedback-service.js'
import {BASE_RULE,createCreditRequests,creditAction,creditOverview,creditAccount,expireCredit} from '../src/utils/credit-service.js'
const seed=JSON.parse(fs.readFileSync(new URL('../src/utils/seed.json',import.meta.url)))
const U={id:1,role:'ROLE_USER'},M={id:1,role:'ROLE_UNIT'},A={id:1,role:'ROLE_ADMIN'}
const N=Date.parse('2026-10-04T12:00:00Z'),UID='y00000101'
const fresh=()=>{const d=structuredClone(seed);d.goods.find(g=>g.id===1).price=20;return d}
const act=(d,a,k,b={},n=N)=>{const before=structuredClone(d);try{return creditAction(d,a,k,b,n)}catch(e){Object.keys(d).forEach(k=>delete d[k]);Object.assign(d,before);throw e}}
function request(d,merchant=1,n=N){let productId=1;if(merchant!==1){productId=1000+merchant;if(!d.goods.some(g=>g.id===productId))d.goods.push({...d.goods.find(g=>g.id===1),id:productId,unitId:merchant,price:20})}const id=Math.max(...d.orders.map(x=>x.id),0)+1;const row={id,goodsId:productId,name:'20元示例套餐',userId:1,unitId:merchant,num:1,price:20,img:'/food/beef-rice.jpg',remark:'少辣'};d.orders.push(row);return createCreditRequests(d,U,[row],n)[0]}
function publish(d,m=M,n=N){const req=request(d,m.id,n);return act(d,m,'publish',{requestId:req.id},n)}
function confirm(d,o,n=N){return act(d,U,'confirm',{orderId:o.id,credential:o.confirmationCredential.credential,version:o.version,snapshotHash:o.snapshotHash,agreementAccepted:true},n)}
function redeem(d,o,m=M,n=N){const c=act(d,U,'fulfillment-code',{orderId:o.id},n);return act(d,m,'redeem',{orderId:o.id,credential:c.credential},n)}
function pay(d,rec,amount,key){return act(d,U,'repay',{receivableIds:[rec.id],merchantUid:rec.merchantUid,amountMinor:amount,clientKey:key})}
function result(d,p,kind='CONFIRMED',eventId='event-'+p.id){return act(d,A,'simulate-result',{personaId:'701',repaymentId:p.id,reference:p.reference,merchantUid:p.merchantUid,amountMinor:p.amountMinor,currency:'CNY',environment:'SIMULATION',providerEventId:eventId,result:kind})}
function account(d){const a=creditAccount(d,UID,N);assert.equal(a.totalMinor,a.reservedMinor+a.principalMinor+a.availableMinor);assert(a.availableMinor>=0);return a}
let passed=0
function test(name,fn){fn();passed++;console.log('PASS',name)}
function fulfilled(){const d=fresh(),o=publish(d);confirm(d,o);redeem(d,o);return {d,o,rec:d.credit.receivables[0]}}
function refund(d,o,amount=1500,key='r'){return act(d,U,'refund-create',{orderId:o.id,requestedMinor:amount,reason:'餐品售后示例',clientKey:key})}
function decision(d,r,decision='APPROVE',key='d'){return act(d,A,'refund-decision',{personaId:'402',refundId:r.id,version:r.version,decision,reason:'独立核对示例',clientKey:key})}
function refundResult(d,r,result='CONFIRMED',eventId='return-'+r.id){return act(d,A,'simulate-refund-result',{personaId:'701',refundId:r.id,reference:r.reference,merchantUid:r.merchantUid,amountMinor:r.returnPayableMinor,currency:'CNY',environment:'SIMULATION',providerEventId:eventId,result})}
test('20 order / 8 paid / 15 refund: 12 principal + 3 cash, independent immutable repayment',()=>{const {d,o,rec}=fulfilled();const p=pay(d,rec,800,'p');result(d,p);const prior=JSON.stringify(p);const r=refund(d,o);assert.equal(account(d).principalMinor,1200);const input={personaId:'402',refundId:r.id,version:r.version,decision:'APPROVE',reason:'核对',clientKey:'decision'};act(d,A,'refund-decision',input);act(d,A,'refund-decision',input);assert.equal(r.principalReductionMinor,1200);assert.equal(r.returnPayableMinor,300);assert.equal(r.status,'PROCESSING');assert.equal(account(d).availableMinor,10000);refundResult(d,r);refundResult(d,r);refundResult(d,r,'CONFIRMED','new-event');assert.equal(r.returnedMinor,300);assert.equal(account(d).availableMinor,10000);assert.equal(JSON.stringify(p),prior);assert.equal(o.status,'FULFILLED');assert.equal(creditOverview(d,M,N).merchantSummary.netReceivedMinor,500)})
test('Full unpaid and fully paid refunds; cash net includes unallocated receipts',()=>{for(const paid of [0,2000,3000]){const {d,o,rec}=fulfilled();if(paid){const p=pay(d,rec,paid,'p');result(d,p)}const r=refund(d,o,2000);decision(d,r);assert.equal(r.principalReductionMinor,paid?0:2000);assert.equal(r.returnPayableMinor,paid?2000:0);if(paid)refundResult(d,r);assert.equal(r.status,'SUCCEEDED');assert.equal(account(d).availableMinor,10000);const m=creditOverview(d,M,N).merchantSummary;assert.equal(m.netReceivedMinor,paid?paid-2000:0);assert.equal(m.unallocatedMinor,Math.max(0,paid-2000))}})
test('Pending caps, rejection and invalid amounts/scope leave accounting unchanged',()=>{const {d,o}=fulfilled();const r=refund(d,o,1500);assert.throws(()=>refund(d,o,501,'over'));for(const amount of [0,-1,NaN,Infinity,1.5])assert.throws(()=>refund(d,o,amount,'bad'));assert.throws(()=>act(d,{id:2,role:'ROLE_USER'},'refund-create',{orderId:o.id,requestedMinor:100,reason:'x',clientKey:'other'}));assert.throws(()=>act(d,{id:2,role:'ROLE_UNIT'},'refund-merchant-response',{refundId:r.id,decision:'SUPPORT',reason:'x'}));assert.equal(account(d).principalMinor,2000);decision(d,r,'REJECT');assert.equal(account(d).principalMinor,2000);assert.equal(refund(d,o,2000,'new').status,'REQUESTED')})
test('Unknown cannot retry; explicit failure replay retries once; late success no duplicate release',()=>{const {d,o,rec}=fulfilled();result(d,pay(d,rec,2000,'p'));const r=refund(d,o,2000);decision(d,r);refundResult(d,r,'TIMEOUT','timeout');assert.throws(()=>act(d,A,'refund-retry',{personaId:'402',refundId:r.id,version:r.version,reason:'x',clientKey:'retry'}));refundResult(d,r,'FAILED','failed');const current=d.credit.refunds.find(x=>x.id===r.id),payload={personaId:'402',refundId:r.id,version:current.version,reason:'核查失败',clientKey:'retry'};act(d,A,'refund-retry',payload);const count=current.history.length;act(d,A,'refund-retry',payload);assert.equal(current.attempt,2);assert.equal(current.history.length,count);assert.throws(()=>act(d,A,'refund-retry',{...payload,reason:'changed'}));const live=d.credit.refunds.find(x=>x.id===r.id);refundResult(d,live);act(d,A,'refund-retry',payload);assert.equal(live.returnedMinor,2000);assert.equal(account(d).availableMinor,10000)})
test('Reviews belong to fulfilled customer; one time / replay; cash unaffected / public after refund and deletion',()=>{const {d,o}=fulfilled(),row=d.orders.find(x=>x.creditOrderId===o.id),input={orderId:row.id,text:'很好 A & B\n值得再来',rate:5,clientKey:'review'};assert.throws(()=>submitReview(d,{id:2,role:'ROLE_USER'},input,N));assert.throws(()=>submitReview(d,U,{...input,rate:0},N));assert.throws(()=>submitReview(d,U,{...input,text:''},N));submitReview(d,U,input,N);submitReview(d,U,input,N);assert.throws(()=>submitReview(d,U,{...input,clientKey:'duplicate'},N));replyReview(d,M,{orderId:row.id,text:'谢谢 A & B\n欢迎再来'},N);assert.ok(row.reply.includes('&amp;'));assert.ok(row.reply.includes('<br>'));assert.equal(account(d).principalMinor,2000);const r=refund(d,o,500);decision(d,r);assert.equal(publicReviews(d,{goodsId:row.goodsId}).filter(x=>x.orderId===row.id).length,1);d.goods=d.goods.filter(g=>g.id!==row.goodsId);assert.equal(publicReviews(d,{unitId:1}).filter(x=>x.orderId===row.id).length,1);assert.equal(feedbackOrders(d,U,{creditOrderId:o.id})[0].canReview,false);assert.equal(feedbackOrders(JSON.parse(JSON.stringify(d)),U,{creditOrderId:o.id})[0].reviewed,true)})
test('Ordinary after-sales persists merchant opinion without pretending a cash refund',()=>{const d=fresh(),row=d.orders.find(o=>o.status==='待评价');row.userId=1;const r=createAfterSales(d,U,{orderId:row.id,requestedMinor:100,reason:'示例售后',clientKey:'ordinary'},N);assert.equal(r.status,'REQUESTED');merchantAfterSales(d,{id:row.unitId,role:'ROLE_UNIT'},{id:r.id,decision:'SUPPORT',reason:'商家同意处理'},N);assert.equal(r.status,'ACCEPTED');assert.equal(r.returnedMinor,0);assert.equal(r.principalReductionMinor,0);assert.equal(r.history.length,2)})
console.log(JSON.stringify({passed,scope:'Refund accounting and review/after-sales regression; source-based integer cents, local only'}))
