// Real Vue DOM → real Java HTTP in a fresh synthetic fixture; not browser-pixel QA.
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {JSDOM} from 'jsdom'
import {createServiceHttpClient} from '../src/utils/service-http.js'
const baseUrl=process.env.SHOP_API_BASE
assert.ok(baseUrl,'Run through verification/with-support-http-fixture.py')
const ok=r=>{assert.equal(r.code,'200',r.msg);return r.data}
async function auth(phone){let token='';const client=createServiceHttpClient({baseUrl,tokenProvider:()=>token});const c=ok(await client.post('/auth/sms-challenges',{phone,purpose:'LOGIN'},{anonymous:true}));token=ok(await client.post('/auth/sessions',{provider:'PHONE_OTP',phone,challengeId:c.challengeId,code:'246810'},{anonymous:true})).accessToken;return {token,client,context:ok(await client.get('/support/context'))}}
const actors=await Promise.all(['SIM-USER-001','SIM-OWNER-001','SIM-SUPPORT-001','SIM-USER-002'].map(auth)),[user,owner,platform,other]=actors
const dom=new JSDOM('<!doctype html><html><body><div id="app"></div></body></html>',{url:'https://mall-test.invalid/#/mall/home',pretendToBeVisual:true})
for(const k of ['window','document','Document','location','history','localStorage','sessionStorage','Node','Element','HTMLElement','SVGElement','HTMLInputElement','HTMLTextAreaElement','HTMLFormElement','Event','CustomEvent','MouseEvent','KeyboardEvent','MutationObserver','DOMParser','FileReader','File','getComputedStyle'])Object.defineProperty(globalThis,k,{value:k==='getComputedStyle'?dom.window[k].bind(dom.window):dom.window[k],configurable:true})
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.requestAnimationFrame=dom.window.requestAnimationFrame.bind(dom.window);globalThis.cancelAnimationFrame=dom.window.cancelAnimationFrame.bind(dom.window);globalThis.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}}
dom.window.matchMedia=()=>({matches:false,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});Element.prototype.scrollTo=function(){}
const downloads=[];dom.window.HTMLAnchorElement.prototype.click=function(){downloads.push({name:this.download,url:this.href})}
const h=await import('../.test-build/harness.mjs'),app=await h.mount(),api=h.request
const wait=()=>new Promise(r=>setTimeout(r,80))
async function until(fn,label){for(let n=0;n<100;n++){await h.nextTick();if(fn())return;await wait()}throw Error('UI timeout '+label+' at '+h.router.currentRoute.value.fullPath+'\n'+document.body.textContent.slice(-1000))}
async function route(path){await h.router.push(path);await wait()}
async function choose(actor,path){await route('/login');await h.attachServiceSession({baseUrl,token:actor.token});await route(path)}
async function click(text){await h.nextTick();const el=[...document.querySelectorAll('button,[role="tab"]')].find(x=>x.textContent.trim()===text);assert.ok(el,'missing button '+text);assert.ok(!el.disabled,'disabled '+text);el.click();await wait()}
async function sel(selector){await until(()=>document.querySelector(selector),'selector '+selector);const el=document.querySelector(selector);assert.ok(!el.disabled,'disabled '+selector);el.click();await wait()}
function input(selector,value){let el=document.querySelector(selector);assert.ok(el,selector);if(!['INPUT','TEXTAREA','SELECT'].includes(el.tagName))el=el.querySelector('input,textarea,select');assert.ok(el,'control '+selector);el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
async function upload(files){const el=document.querySelector('[data-testid="service-upload-input"]');assert.ok(el);Object.defineProperty(el,'files',{value:files,configurable:true});el.dispatchEvent(new Event('change',{bubbles:true}));await until(()=>document.querySelectorAll('.upload-file-row').length===files.length,'uploaded metadata');assert.ok(!document.querySelector('.service-upload>p[role="alert"]'))}
async function submit(selector){const el=document.querySelector(selector);assert.ok(el,selector);el.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await wait()}
try{
 await choose(user,'/mall/support');await until(()=>document.querySelector('.support-entry-grid'),'service center');await sel('.support-entry-grid button:first-child');await until(()=>document.querySelector('.support-store-picker .support-session'),'authorized server shop');await sel('.support-store-picker .support-session');await until(()=>h.router.currentRoute.value.path==='/mall/supportChat'&&document.querySelector('[data-testid="customer-support-composer"]'),'opened chat');const sessionId=h.router.currentRoute.value.query.id
 input('[aria-label="给本店发消息"]','Vue真实HTTP：请问套餐可以少辣吗？');await upload([new File([fs.readFileSync('public/brand/favicon-v5.png')],'actual-ui.png',{type:'image/png'})]);await submit('[data-testid="customer-support-composer"]');await until(()=>document.querySelector('.support-message')?.textContent.includes('少辣'),'stored customer message')
 assert.equal(ok(await owner.client.get('/support/session',{params:{id:sessionId}})).messages[0].text,'Vue真实HTTP：请问套餐可以少辣吗？')
 assert.notEqual((await other.client.get('/support/session',{params:{id:sessionId}})).code,'200')
 await choose(owner,'/merchant/support');await sel('[data-testid="support-session-row"]');await until(()=>document.querySelector('[data-testid="support-message-list"]')?.textContent.includes('少辣'),'merchant reads');input('[data-testid="support-message-input"]','服务端本店回复：可以少辣');await sel('[data-testid="support-send-message"]');await until(()=>document.querySelector('[data-testid="support-message-list"]')?.textContent.includes('可以少辣'),'merchant writes')
 await choose(user,'/mall/supportChat?id='+sessionId);await until(()=>document.querySelector('.support-messages')?.textContent.includes('服务端本店回复'),'user reads server reply')
 await route('/mall/supportNew?unitId='+user.context.shops[0].unitId);await until(()=>document.querySelector('[data-testid="customer-ticket-form"]'),'ticket form');input('[aria-label="留言标题"]','多附件真实HTTP工单'+ '长标题'.repeat(30));input('[aria-label="留言内容"]','上传PDF、文字和MP4，核对后端保存及角色处理');input('[aria-label="处理优先级"]','HIGH')
 await upload([new File([fs.readFileSync('public/manual-assets/customer-manual.pdf')],'manual.pdf',{type:'application/pdf'}),new File(['synthetic note'],'note.txt',{type:'text/plain'}),new File([fs.readFileSync('tests/fixtures/short-demo.mp4')],'short.mp4',{type:'video/mp4'})]);await submit('[data-testid="customer-ticket-form"]');await until(()=>h.router.currentRoute.value.path==='/mall/supportTicket'&&document.querySelector('.support-ticket-state'),'ticket saved');const ticketId=h.router.currentRoute.value.query.id
 const t=ok(await user.client.get('/support/ticket',{params:{id:ticketId}}));assert.equal(t.attachments.length,3);assert.equal(t.priority,'HIGH');assert.ok(t.title.length>80);assert.equal(document.querySelectorAll('[data-testid="service-attachment"]').length,3)
 await click('加载视频预览');await until(()=>document.querySelector('video')?.src.startsWith('blob:'),'actual video blob');await sel('[aria-label="下载附件"]');assert.ok(downloads.length);assert.ok(downloads[0].url.startsWith('blob:'))
 await choose(owner,'/merchant/support');await sel('[data-testid="support-tickets-tab"]');await sel('[data-testid="support-open-ticket"]');await until(()=>document.querySelector('[data-testid="support-ticket-reply-input"]'),'ticket detail');input('[data-testid="support-ticket-reply-input"]','本店已核对，附件已收到');await sel('[data-testid="support-reply-ticket"]');await until(()=>document.querySelector('[data-testid="support-ticket-reply"]')?.textContent.includes('已收到'),'merchant ticket reply');await sel('[data-testid="support-advance-ticket"]');await until(()=>document.querySelector('[data-testid="support-ticket-current-status"]')?.textContent==='处理中','progress');await sel('[data-testid="support-advance-ticket"]');await until(()=>document.querySelector('[data-testid="support-ticket-current-status"]')?.textContent==='已解决','resolve')
 await choose(user,'/mall/supportTicket?id='+ticketId);await until(()=>document.querySelector('.support-ticket-reply')?.textContent.includes('已收到'),'customer progress');await click('归档（可恢复）');await until(()=>document.querySelector('.support-ticket-state')?.textContent.includes('已归档'),'archived');assert.notEqual((await owner.client.get('/support/ticket',{params:{id:ticketId}})).code,'200');assert.notEqual((await owner.client.get('/support/attachments/download',{params:{id:t.attachments[0].id}})).code,'200');await click('恢复留言');await until(()=>!document.querySelector('.support-ticket-state')?.textContent.includes('已归档'),'restored')
 await choose(platform,'/platform/support');await sel('[data-testid="support-tickets-tab"]');await sel('[data-testid="support-open-ticket"]');input('[data-testid="support-ticket-reply-input"]','平台通过实际HTTP补充记录');await sel('[data-testid="support-reply-ticket"]');await until(()=>document.querySelector('.ticket-replies')?.textContent.includes('实际HTTP补充'),'platform reply');assert.equal(ok(await user.client.get('/support/ticket',{params:{id:ticketId}})).replies.length,2)
 await choose(user,'/mall/profile');await until(()=>document.querySelector('.profile-editor input[disabled]')?.value=== 'SIM-USER-001','real username');input('.profile-editor input[placeholder="请输入昵称"]','UI联调显示昵称');await click('保存服务端资料');await until(()=>h.router.currentRoute.value.path==='/mall/support','profile route');assert.equal(ok(await user.client.get('/support/profile')).nickname,'UI联调显示昵称')
 await route('/mall/bill');assert.ok(document.querySelector('.native-device'));assert.ok(document.querySelector('.native-app').textContent.includes('尚未接入Java服务'));assert.equal(localStorage.getItem('mall-ui-data-v2'),null,'backend must not fall back to local storage')
 console.log('PASS rendered Vue→real Java HTTP: server identity/store IDs, chat image/upload/reply/read, 3 file kinds, >80char title/HIGH, versioned merchant processing, owner archive/restore and attachment revocation, platform reply, own profile; no local fallback')
}finally{app.unmount();dom.window.close()}
