import assert from 'node:assert/strict'
import fs from 'node:fs'
import {BASE_RULE,createCreditRequests,creditAction,creditOverview,creditAccount,expireCredit} from '../src/utils/credit-service.js'
const seed=JSON.parse(fs.readFileSync(new URL('../src/utils/seed.json',import.meta.url)))
const U={id:1,role:'ROLE_USER'},M={id:1,role:'ROLE_UNIT'},A={id:1,role:'ROLE_ADMIN'}
const N=Date.parse('2026-10-04T12:00:00Z'),UID='y00000101'
const fresh=()=>{const d=structuredClone(seed);d.goods.find(g=>g.id===1).price=20;return d}
const act=(d,a,k,b={},n=N)=>{const before=structuredClone(d);try{return creditAction(d,a,k,b,n)}catch(e){Object.keys(d).forEach(k=>delete d[k]);Object.assign(d,before);throw e}}
function request(d,merchant=1,n=N){let productId=1;if(merchant!==1){productId=1000+merchant;if(!d.goods.some(g=>g.id===productId))d.goods.push({...d.goods.find(g=>g.id===1),id:productId,unitId:merchant,price:20})}const id=Math.max(...d.orders.map(x=>x.id),0)+1;const row={id,goodsId:productId,name:'20元示例套餐',unitId:merchant,num:1,price:20,img:'/food/beef-rice.jpg',remark:'少辣'};d.orders.push(row);return createCreditRequests(d,U,[row],n)[0]}
function publish(d,m=M,n=N){const req=request(d,m.id,n);return act(d,m,'publish',{requestId:req.id},n)}
function confirm(d,o,n=N){return act(d,U,'confirm',{orderId:o.id,credential:o.confirmationCredential.credential,version:o.version,snapshotHash:o.snapshotHash,agreementAccepted:true},n)}
function redeem(d,o,m=M,n=N){const c=act(d,U,'fulfillment-code',{orderId:o.id},n);return act(d,m,'redeem',{orderId:o.id,credential:c.credential},n)}
function pay(d,rec,amount,key){return act(d,U,'repay',{receivableIds:[rec.id],merchantUid:rec.merchantUid,amountMinor:amount,clientKey:key})}
function result(d,p,kind='CONFIRMED',eventId='event-'+p.id){return act(d,A,'simulate-result',{personaId:'701',repaymentId:p.id,reference:p.reference,merchantUid:p.merchantUid,amountMinor:p.amountMinor,currency:'CNY',environment:'SIMULATION',providerEventId:eventId,result:kind})}
function account(d){const a=creditAccount(d,UID,N);assert.equal(a.totalMinor,a.reservedMinor+a.principalMinor+a.availableMinor);assert(a.availableMinor>=0);return a}
let passed=0
function test(name,fn){fn();passed++;console.log('PASS',name)}
test('Source fixture values and exact reserve → principal → partial/full repayment',()=>{let d=fresh();assert.deepEqual(BASE_RULE,{code:'RV-SIM-TEST-001',quotaMinor:10000,transactionMaxMinor:2000,termDays:30,credentialTtlSeconds:300,reservationTtlSeconds:900,fixtureOnly:true,formalApproval:false});const o=publish(d);assert.equal(account(d).availableMinor,10000);confirm(d,o);assert.equal(account(d).reservedMinor,2000);assert.equal(account(d).principalMinor,0);assert.equal(account(d).availableMinor,8000);redeem(d,o);assert.equal(account(d).reservedMinor,0);assert.equal(account(d).principalMinor,2000);const rec=d.credit.receivables[0];assert.equal(Date.parse(rec.dueAt),N+30*86400000);const p=pay(d,rec,800,'p1');assert.equal(p.status,'PENDING');assert.equal(account(d).principalMinor,2000);result(d,p);assert.equal(account(d).principalMinor,1200);assert.equal(account(d).availableMinor,8800);assert.equal(rec.status,'PARTIAL');result(d,p);result(d,p,'CONFIRMED','event-new-same-ref');assert.equal(account(d).principalMinor,1200);const p2=pay(d,rec,1200,'p2');result(d,p2);assert.equal(account(d).principalMinor,0);assert.equal(account(d).availableMinor,10000);assert.equal(rec.status,'SETTLED');assert.equal(o.status,'FULFILLED')})
test('Only customer confirms; only matching merchant publishes/redeems',()=>{const d=fresh(),req=request(d);assert.throws(()=>act(d,U,'publish',{requestId:req.id}));assert.throws(()=>act(d,{id:2,role:'ROLE_UNIT'},'publish',{requestId:req.id}));const o=act(d,M,'publish',{requestId:req.id});assert.throws(()=>act(d,M,'confirm',{orderId:o.id}));confirm(d,o);const c=act(d,U,'fulfillment-code',{orderId:o.id});assert.throws(()=>act(d,{id:2,role:'ROLE_UNIT'},'redeem',{orderId:o.id,credential:c.credential}));assert.equal(account(d).reservedMinor,2000)})
test('Confirmation requires active consent and matching snapshot; replay holds once',()=>{const d=fresh(),o=publish(d);assert.throws(()=>act(d,U,'confirm',{orderId:o.id,credential:o.confirmationCredential.credential,version:o.version,snapshotHash:o.snapshotHash}));const input={orderId:o.id,credential:o.confirmationCredential.credential,version:o.version,snapshotHash:o.snapshotHash,agreementAccepted:true};act(d,U,'confirm',input);act(d,U,'confirm',input);assert.equal(d.credit.reservations.length,1);assert.equal(account(d).reservedMinor,2000)})
test('Cancellation/expiry release exactly once and old code cannot redeem',()=>{let d=fresh(),o=publish(d);confirm(d,o);act(d,U,'cancel',{orderId:o.id});act(d,U,'cancel',{orderId:o.id});assert.equal(account(d).availableMinor,10000);d=fresh();o=publish(d);confirm(d,o);const c=act(d,U,'fulfillment-code',{orderId:o.id});expireCredit(d,N+901000);expireCredit(d,N+901000);assert.equal(d.credit.reservations[0].status,'EXPIRED');assert.equal(creditAccount(d,UID,N+901000).availableMinor,10000);assert.throws(()=>act(d,M,'redeem',{orderId:o.id,credential:c.credential},N+901000))})
test('Reissued fulfillment code invalidates previous code; fulfillment is idempotent',()=>{const d=fresh(),o=publish(d);confirm(d,o);const first=act(d,U,'fulfillment-code',{orderId:o.id}),second=act(d,U,'fulfillment-code',{orderId:o.id});assert.throws(()=>act(d,M,'redeem',{orderId:o.id,credential:first.credential}));act(d,M,'redeem',{orderId:o.id,credential:second.credential});act(d,M,'redeem',{orderId:o.id,credential:second.credential});assert.equal(d.credit.receivables.length,1);assert.throws(()=>act(d,U,'cancel',{orderId:o.id}));assert.equal(account(d).principalMinor,2000)})
test('Cross-merchant reservations share one user limit, while merchant projection hides it',()=>{const d=fresh();for(let i=1;i<=5;i++){const o=publish(d,{id:i,role:'ROLE_UNIT'});confirm(d,o)}assert.equal(account(d).availableMinor,0);const extra=publish(d,{id:6,role:'ROLE_UNIT'});assert.throws(()=>confirm(d,extra));const merchant=creditOverview(d,M,N);assert.equal(merchant.account,undefined);assert.equal(merchant.accounts,undefined);assert.equal(merchant.orders.length,1);assert.equal(merchant.merchantSummary.reservedMinor,2000)})
test('Submission does not repay; timeout is unknown; late success waits for independent review',()=>{const d=fresh(),o=publish(d);confirm(d,o);redeem(d,o);const rec=d.credit.receivables[0],p=pay(d,rec,800,'late');result(d,p,'TIMEOUT','timeout');assert.equal(p.status,'PENDING');assert.equal(p.channelResult,'UNKNOWN');result(d,p,'FAILED','failed');result(d,p,'CONFIRMED','late');assert.equal(p.status,'EXCEPTION');assert.equal(account(d).principalMinor,2000);assert.equal(p.unallocatedMinor,800);assert.throws(()=>act(d,U,'resolve-exception',{repaymentId:p.id,personaId:'402'}));const review=act(d,A,'request-exception-resolution',{repaymentId:p.id,personaId:'401',evidence:'核对模拟回调、剩余本金和商家'});act(d,A,'resolve-exception',{resolutionId:review.id,personaId:'402'});assert.equal(account(d).principalMinor,1200);act(d,A,'resolve-exception',{resolutionId:review.id,personaId:'402'});assert.equal(account(d).principalMinor,1200)})
test('Overpayment is unallocated/refundable, never extra user quota',()=>{const d=fresh(),o=publish(d);confirm(d,o);redeem(d,o);const p=pay(d,d.credit.receivables[0],3000,'over');result(d,p);assert.equal(p.unallocatedMinor,1000);assert.equal(account(d).availableMinor,10000)})
test('Wrong callback identity fields rejected and no user can inject success',()=>{const d=fresh(),o=publish(d);confirm(d,o);redeem(d,o);const p=pay(d,d.credit.receivables[0],100,'wrong');assert.throws(()=>act(d,U,'simulate-result',{personaId:'701',repaymentId:p.id}));assert.throws(()=>act(d,A,'simulate-result',{personaId:'701',repaymentId:p.id,reference:p.reference,merchantUid:p.merchantUid,amountMinor:999,currency:'CNY',environment:'SIMULATION',providerEventId:'wrong',result:'CONFIRMED'}));assert.equal(account(d).principalMinor,2000)})
test('Rule independent approval, occupied limit guard, and immutable old-order term',()=>{const d=fresh(),o=publish(d);confirm(d,o);const bad=act(d,A,'draft-rule',{personaId:'401',quotaMinor:1000,transactionMaxMinor:1000,termDays:7,credentialTtlSeconds:300,reservationTtlSeconds:900});assert.throws(()=>act(d,A,'approve-rule',{personaId:'401',ruleId:bad.id}));assert.throws(()=>act(d,A,'approve-rule',{personaId:'402',ruleId:bad.id}));const good=act(d,A,'draft-rule',{personaId:'401',quotaMinor:10000,transactionMaxMinor:2000,termDays:7,credentialTtlSeconds:300,reservationTtlSeconds:900});act(d,A,'approve-rule',{personaId:'402',ruleId:good.id});redeem(d,o);assert.equal(Date.parse(d.credit.receivables[0].dueAt),N+30*86400000)})
test('Dispute and overdue block new confirmations but allow repayment',()=>{const d=fresh(),o=publish(d);confirm(d,o);redeem(d,o);const rec=d.credit.receivables[0];const dispute=act(d,U,'dispute',{receivableId:rec.id,reason:'演示核对金额'});assert.equal(account(d).blocked,true);const next=publish(d);assert.throws(()=>confirm(d,next));act(d,A,'resolve-dispute',{personaId:'501',disputeId:dispute.id,resolution:'演示已核对'});assert.equal(account(d).blocked,false);assert.equal(creditAccount(d,UID,N+31*86400000).overdue,true);assert.equal(pay(d,rec,100,'dispute-payment').status,'PENDING')})
test('Original rule bounds reject every out-of-range parameter',()=>{for(const patch of [{quotaMinor:1000001},{transactionMaxMinor:1000001},{termDays:366},{credentialTtlSeconds:1},{credentialTtlSeconds:601},{reservationTtlSeconds:1},{reservationTtlSeconds:3601}]){const d=fresh();assert.throws(()=>act(d,A,'draft-rule',{personaId:'401',...BASE_RULE,...patch}))}})
test('Success after UNKNOWN clears its display marker and changed-event payload rejects',()=>{const d=fresh(),o=publish(d);confirm(d,o);redeem(d,o);const p=pay(d,d.credit.receivables[0],2000,'unknown');result(d,p,'TIMEOUT','unknown');assert.throws(()=>result(d,p,'CONFIRMED','unknown'));result(d,p,'CONFIRMED','success');assert.equal(d.credit.repayments[0].channelResult,'CONFIRMED');assert.equal(account(d).principalMinor,0)})
console.log(JSON.stringify({passed,scope:'Pure local contract-state tests; integer cents, source fixture parameters; no real payments'}))
